functionality of: put/delete/post/get/getById methods. Validartions b…
MaksymilianBilski/goit-node.js-02 pull request #2
Opened 2023-03-10 14:49 UTC by MaksymilianBilski

…y using Joi

2023-03-11 16:37 UTC, iddux commented
Brak prefixa `/api/contacts` dla endpointów jest np. `/:id` zamiast `/api/contacts/:id`

2023-03-11 16:47 UTC, iddux requested changes

2023-03-11 16:47 UTC, iddux commented on app.js
> +app.use("/", contactsRouter);
brak prefixa `api/contacts` dla każdego z endpointów, sugerowałbym podmienić na 

`app.use('api/contacts'), contactsRouter);`

2023-03-11 16:47 UTC, iddux commented on models/contacts.js
> +      tlds: { allow: ["com", "net", "pl", "org"] },
Rozumiem walidacje emaila, ale co by się stało gdyby ktoś chciał użyć maila z inną domeną np. uk :smile:. Na ten moment możemy zostawić tne kod w takiej formie :D

2023-03-11 16:47 UTC, iddux commented on models/contacts.js
> -// const fs = require('fs/promises')
do usunięcia

2023-03-11 16:47 UTC, iddux commented on routes/api/contacts.js
> +  if (response === "undefined") {
zamiast sprawdzania czy response jest undefined, możemy to uprościć przy użyciu takiego warunku if(!response)

2023-03-11 16:47 UTC, iddux commented on routes/api/contacts.js
> +    res.json({
wszystkie użycia `res.json` są nieprawidłowo skonsturowane, ponieważ nagłówek HTTP w każdym przypadku wynosi `200 `, co nie jest prawidłowe. sutgerowałbym przesyłać response w nastepujący sposób. 

np. `res.status(kod statusu).json({message: 'tresc wiadomosci})`

jak widzisz `status` oraz `code` nie musi byc wysyłany do metody `json` - wystarczy dodać metodę `.status(kod http) i status zostanie dodany jako http response status code

Proszę o zastosowanie tych zmian do wszystkich endpointów.

2023-03-11 16:54 UTC, MaksymilianBilski commented on models/contacts.js
> -// const fs = require('fs/promises')
No ale jak to? Ja potem korzystam z fs, żeby pracować z plikiem contacts.json

2023-03-11 16:59 UTC, MaksymilianBilski commented on routes/api/contacts.js
> +  if (response === "undefined") {
No tylko problem jest w tym, że jeśli przekazuje undefined jako wartość, a nie jako string to mi się appka crashuje: "SyntaxError: "undefined" is not valid JSON"

2023-03-12 06:51 UTC, iddux commented on models/contacts.js
> -// const fs = require('fs/promises')
Mój błąd, nie zauważyłem że ta linijka została nadpisana.

2023-03-12 07:00 UTC, iddux commented on routes/api/contacts.js
> +  if (response === "undefined") {
rozumiem, dzieje się tak ponieważ masz customową logikę, która parsuje JSON do stringa w funkcji `getContactById` w `models/contacts` 

w tej funkcji, gdy element nie jest znaleziony to wartość "undefined" jest zamieniana na stringa za pomoca metody `JSON.stringify` .

nie ma potrzeby tego robić, wystarczy aby funkcja `getContactById` wyglądała tak: 


`
const getContactById = async (contactId) => {
  const list = await listContacts();
  const searchedElement = list.find(
    (el) => el.id.toString() === contactId.toString()
  );
  
  return searchedElement;
};
`

2023-03-12 07:29 UTC, MaksymilianBilski commented on routes/api/contacts.js
> +  if (response === "undefined") {
Zrobiłem tak jak napisałeś ale dalej leciało to samo. Problem jednak był w tym, że nie dałem return w routes\api\contacts.js w metodzie get. Tym samym dodałem wszędzie brakujące returny przed metodami res.json

2023-03-13 15:31 UTC, merged